version: '3.6'

services:
  postgres:
    image: postgres:14
    container_name: supabase-db
    restart: always
    environment:
      POSTGRES_PASSWORD: supabase
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"

volumes:
  dbdata:
