services:
  postgres:
    image: postgres:14
    container_name: supabase-db
    restart: always
    ports:
      - "54322:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  studio:
    image: supabase/studio:latest
    container_name: supabase-studio
    ports:
      - "8080:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 20

environment:

# ---------- POSTGRES ----------
POSTGRES_USER=postgres
POSTGRES_PASSWORD=supabase
POSTGRES_DB=postgres
POSTGRES_PORT=54322

# ---------- SUPABASE STUDIO ----------
SUPABASE_URL=http://localhost:8080
SUPABASE_ANON_KEY=92ydXL1u7o6+7+8aYCbXh7s9BwTU/CJQ+pFvvR6Tgt4=
SUPABASE_SERVICE_KEY=92ydXL1u7o6+7+8aYCbXh7s9BwTU/CJQ+pFvvR6Tgt4=
SUPABASE_JWT_SECRET=92ydXL1u7o6+7+8aYCbXh7s9BwTU/CJQ+pFvvR6Tgt4=
STUDIO_PORT=8080

# This is used by Supabase Studio to connect to the Postgres DB
POSTGRES_URL=postgres://postgres:supabase@postgres:5432/postgres

SUPABASE_DB_HOST=postgres
SUPABASE_DB_PORT=5432
SUPABASE_DB_NAME=postgres
SUPABASE_DB_USER=postgres
SUPABASE_DB_PASSWORD=supabase

volumes:
  dbdata:






