services:
  postgres:
    image: postgres:14
    container_name: supabase-db
    restart: always
    ports:
      - "54322:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  studio:
    image: supabase/studio:latest
    container_name: supabase-studio
    ports:
      - "8080:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  dbdata:






