version: '3.6'

services:
  postgres:
    image: postgres:14
    container_name: supabase-db
    restart: always
    environment:
      POSTGRES_PASSWORD: supabase
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"

  studio:
    image: supabase/studio:2024.04.01
    container_name: supabase-studio
    ports:
      - "8080:3000"
    depends_on:
      - postgres
    environment:
      SUPABASE_URL: http://localhost:54322

volumes:
  dbdata:

