services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: supabase
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"

  studio:
    image: supabase/studio:latest
    container_name: supabase-studio
    ports:
      - "8080:3000"
    depends_on:
      - postgres
    environment:
      SUPABASE_URL: http://postgres:5432

volumes:
  dbdata:


